# Generated by Django 4.0.3 on 2022-03-24 19:24

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_processedvideo_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedvideo',
            name='video',
            field=models.FileField(upload_to='processed_video/%y', validators=[video.validators.process_file_size]),
        ),
    ]
