# Generated by Django 4.0.3 on 2022-03-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_processedvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedvideo',
            name='video',
            field=models.FileField(upload_to='processed_video/%y'),
        ),
    ]
